# Generated by Django 5.0.1 on 2024-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Placed'), (4, 'Shipped'), (5, 'Delivered')], default='Pending', max_length=10),
        ),
    ]
